### ISSUE TITLE
logging to file with name created from unescaped chars in nick can't be unsecure 

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#100]
I notice then some user has slash in nickname, talk with such user creates dir inseatd of file, in this dir was created file ".log". What would happen if user has name "../../.bashrc" ;) Or "drop database;" ;)

**Comment by xavery** [comment]
Damn, I relied on the validator function written earlier and assumed that the server rejects nicknames that don't pass this regex. However, I successfully entered a chatroom via the website with a username like `../../usr/bin`, so my function is clearly wrong.

Does replacing `.` and `/` with `@` sound okay to you? It's still disallowed by czateria, so there shouldn't be any name clashes with other nicks if those characters were replaced with something allowable - for example `_` which was the first one to think of.

**Comment by Arek-Arek** [comment]
Is it needed to disallow `.`? Probably should be enough to replace `/` with `@`. And it's fine for me.
