### ISSUE TITLE
FR: change window name to notify about activity

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#2]
When application is minimalised we don't know that there is some activity in chat windows, we can miss priv message we received.

**Comment by xavery** [comment]
Just FYI, commit 8c4da9f56e9bc7720c35dea4ada85b98ed795961 added support for window notifications, which are usually implemented by flashing the application's entry in the taskbar. [Here's how it looks like](https://imgur.com/a/XjaNhd3) on my XFCE panel, but do note that this depends on the used theme. The effect is similar on Windows 7.
This has always been enough for me, so I've never considered adding an extra symbol to the window title - I just wanted to make sure that you're aware of this.

**Comment by Arek-Arek** [comment]
When new user private chat is going to start I see notification but it there is no notification when message arrive in accepted private chat. This is tested on Ubuntu 18 with LXC as wm.
I compare how your client works with how czateria looks on web browser and this is what is worth to implement in my opinion.

**Comment by Arek-Arek** [comment]
Also I noticed that incoming new private conversation moves window to first plan and steal cursor, it can be inconvienient when we write something while this happens.

**Comment by xavery** [comment]
I created #14 to track the thing about private conversation notifications. The original issue should now be solved.
