### ISSUE TITLE
Tab with private chat isn't created

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#25]
When somebody send mi priv chat invitations, I accpet it but new tab, with priv, doesn't appear.

**Comment by xavery** [comment]
Can't reproduce directly, but I've been getting weird random crashes which are probably related to db684af5b56ea32d422caeb23c6b75ad6126febc. There's something going on.

**Comment by xavery** [comment]
Can you try building a debug version of the [`fix-25`](https://github.com/xavery/czateria/tree/fix-25) branch and running it with `CZATERIA_DEBUG`? Thanks.

**Comment by Arek-Arek** [comment]
```
[    40.609] debug {"users":[{"login":"T","emotion":0,"privs":0,"isMailCzateria":0,"perm":1,"hasPrivateCamera":false,"hasOldPublicCamera":false,"isMobileUser":false,"hasNewPublicCamera":false}],"code":128}
[    40.609] debug {"userName":"T","bornDate":"","reasonId":0,"sex":"\u0000","description":"","searchSex":"\u0000","searchAgeFrom":0,"searchAgeTo":0,"uid":15897489,"lon":-122400,"lat":51496399,"token":"866762133","avatarId":"","code":184}
[    49.916] debug {"code":1003}
[    58.688] debug {"users":[{"login":"gość_56029150","emotion":0,"privs":0,"isMailCzateria":0,"perm":0,"hasPrivateCamera":false,"hasOldPublicCamera":false,"isMobileUser":false,"hasNewPublicCamera":false}],"code":128}
[    58.689] debug {"userName":"gość_56029150","bornDate":"","reasonId":0,"sex":"\u0000","description":"","searchSex":"\u0000","searchAgeFrom":0,"searchAgeTo":0,"uid":0,"lon":0,"lat":0,"token":"866763265","avatarId":"0","code":184}
[    61.504] debug {"login":"T","code":130}
[    62.576] debug {"subcode":1,"user":"gość_56029150","type":0,"imgWidth":0,"imgHeight":0,"msg":"asdasd","msgColorId":0,"msgIsBold":false,"msgIsItalic":false,"msgIsUnderline":false,"msgFontTypeId":0,"msgStyleId":0,"nickColorId":0,"code":97}
[    62.584] debug "gość_56029150" message box shown
[    62.786] debug {"user":"gość_56029150","hasPrivs":1,"code":137}
^C
```

tab with private chat didn't appear.

**Comment by Arek-Arek** [comment]
It looks there is no difference if I accept or reject priv. Also sender of invitation doesn't get information about rejection.

**Comment by xavery** [comment]
I reproduced this with Qt 5.9 : weirdly, it doesn't occur with 5.14 which I use normally. Will investigate further.

**Comment by Arek-Arek** [comment]
On the latest commit on fix-25 works for me.

**Comment by xavery** [comment]
Yes, it looks like `QMessageBox` doesn't emit `accepted` and `rejected` signals in Qt 5.9 for some reason. Using `finished` instead seems to fix it, though I really wonder why that is.
Anyway, I'm going to merge it once the build passes, as it seems like something's off with the GitHub runners or the "Install Qt" action.
