### ISSUE TITLE
Autojoin

### ISSUE THREAD

**Issue by xavery** [xavery/czateria#28]
It should be possible to choose a set of rooms to join automatically after launching the program.

Suggested in #3.

**Comment by xavery** [comment]
Fixed by #51.

**Comment by Arek-Arek** [comment]
Thank you:)

>  I think it would be simpler to just have a central "identities" list, with one of these identities being simply chosen for autojoining a given channel or set of channels.

I like this idea.
Now I'm trying to learn how to use this feature in my "chatflow" ;) Is it possible to add run switch to disable autojoin? When I launch new instance of `ui` this doubles session now.
What do you think about a kind of ratelimit when autojoining happens?
