### ISSUE TITLE
After invitation reject can't talk to this person later

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#29]
When I reject first invitation to private talk, next messages from other person are ignored (doesn't create window with question "no"/"yes") and I can't write to this person if I want initiate priv chat.
Prepare logs?

**Comment by Arek-Arek** [comment]
Please try following scenario:
- run ui, log in using two nicknames
- using first user write to second one
- reject invitation
- without closing tab with invitation from first user try write again to second user

I couldn't send a message.

**Comment by xavery** [comment]
There's [code to handle this explicitly](https://github.com/xavery/czateria/blob/master/czatlib/chatsession.h#L35) (i.e. a message can be sent only when waiting for a reply to an invite or if it's active), so I guess I must've had some reason to do it this way. Sending the conversation request again is possible after reopening the tab.
However, the site allows sending a new message - and thus a new request in this situation - without opening a new tab, so this should be fixed.

**Comment by Arek-Arek** [comment]
Thank you. It works in half way ;) When person with I talk closes priv then I can't write to him without closing tab with priv and opening it again.

**Comment by xavery** [comment]
Should be fine now - you only mentioned rejection, so the fix was limited to that particular situation.
