### ISSUE TITLE
FR: ignored users list kept in file

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#3]
It would be usefull to have list of ignored users in file. It would save the time when we join chat again, all "smart" users will be already ignored.

**Comment by xavery** [comment]
The application already creates a settings file, so I guess it makes sense to keep the ignored users list in there. I'll have to implement ignoring itself in the first place, though.

**Comment by Arek-Arek** [comment]
What do you think about function "preferred room" - when user login such preferred room would be opened automatically?
And... regexp in ignored users list (wisienka na torcie:P) :)

**Comment by xavery** [comment]
Implemented in current master.

**Comment by Arek-Arek** [comment]
Woooohooo! What a suprise!
Have you an idea how to edit @VAriant from cli under linux? Is any tool to make it easier?

**Comment by xavery** [comment]
Not really. Settings files aren't meant to be edited outside of Qt. I can implement another `ChatBlocker` interface that's based on flat files, say, one regex per line - would that be okay for you?
