### ISSUE TITLE
Can't join to more than one room using custom, unregistered nickname

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#30]
Hi,
when I choose "nickname only" I can't join to more than one room. I get message "nick already registered".

**Comment by xavery** [comment]
This is a server limitation. I'm getting the same error when trying to do the same thing via the website.

**Comment by Arek-Arek** [comment]
It works for me. I run one web browser instance, login to chat with temporary own nick and I can open many rooms inside (tab "POKOJE" beside "OSOBY").

**Comment by xavery** [comment]
Okay, that explains a lot - this way, the current login session is reused and entering a new captcha thus isn't needed. I'll look into implementing this, but doing this properly would probably require some GUI changes in order to keep track of open sessions and the nicknames they're using.

**Comment by Arek-Arek** [comment]
This was the biggest commit! :) Other commits was very small, I was suprised.
I suspect that this commits brings new issue. After 3600 seconds connection to czateria are finished, relogin fails. 
```
[  3628.881] debug {"user":".Olga37!DlaNiej.","hasPrivs":1,"code":137}
[  3628.985] debug {"data":{"0":"767ee8859538a401d2f12f13ecae4da1","1":"go\u015b\u0107331657","userPerm"
:1,"loginDate":"27-01-2020,20:10:41","settings":{"NICK_COLOUR":"0","MAX_PRIVS":"7"}},"status":1,"code":1
,"msg":"OK"}
[  3629.184] debug {"code":138}
[  3629.184] info Unhandled WebSocket message :
 {"code":138}
[  3629.191] debug {"code":138}
[  3629.191] info Unhandled WebSocket message :
 {"code":138}
[  3629.191] debug {"code":138}
[  3629.191] info Unhandled WebSocket message :
 {"code":138}
[  3629.191] debug {"code":138}
[  3629.192] info Unhandled WebSocket message :
 {"code":138}
[  3629.201] debug {"code":138}
[the same repeateded many times]
[  3629.301] debug {"code":138}
[  3629.301] info Unhandled WebSocket message :
 {"code":138}
[  3629.322] debug {"subcode":26,"id":0,"isAnyRegShowAlready":false,"detailsCode":0,"type":18,"time":0,"admin":"","code":150}
[  3630.649] debug {"code":1003}
[  3633.651] debug {"code":1003}
[  3633.651] debug {"code":1003}
```

**Comment by xavery** [comment]
Yeah, I kind of expected that - the reconnection code is still kind-of-not-really-working, and as you've probably noticed, I don't have any real idea what's exactly wrong.
I'll have to come up with some kind of better testing for this, as waiting that much time for the server to disconnect us is simply absurd. Unfortunately, doing this right would require rather significant changes to make the whole network-interacting code testable, or at least make it connect to a locally-running simulator instead of the actual servers.
