### ISSUE TITLE
Registered nick doesn't see any user in room

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#4]
When I login using registered user (login+pass), room is empty, user lists is empty, can't see any public chat. On console I'm getting message: 

`"{\"subcode\":1,\"id\":0,\"isAnyRegShowAlready\":false,\"detailsCode\":0,\"type\":0,\"time\":0,\"code\":150}"
`

**Comment by Arek-Arek** [comment]
This also happens if I choose own non-registered nick. It looks than only "gość" works.

**Comment by xavery** [comment]
Sorry, can't reproduce - I use a non-registered nick practically every time I use the program. Does this happen with all channels? Can you join them when using the website?

**Comment by Arek-Arek** [comment]
Yeah, using webbrowser I can join using registered user and I can see public talks and users. It happen with all channels, no matter how  many users is in room.

**Comment by xavery** [comment]
I wasn't able to reproduce this - unless you share the exact nickname you're using and the channel that you're trying to join, I'm afraid I won't be of much help.
You could also collect some traffic on your side and send a log to me. Let me know if you're up to it and I'll probably write a freely accessible Wiki article about this.

**Comment by Arek-Arek** [comment]
The best thing is you are willing to develop czateria!
How can I collect traffic? Should I do MITM on websocket traffic?

**Comment by xavery** [comment]
That would also work, but fortunately there's a much easier way, using Chrome's devtools in version 76 or newer . I'll let you know once the guide is ready.

**Comment by xavery** [comment]
Alright, I pushed the changes which are necessary for `qDebug` to print all raw JSON data received/sent from/to the server. Please follow the instructions in [this article](https://github.com/xavery/czateria/wiki/Capturing-messages) to capture the needed data.

**Comment by Arek-Arek** [comment]
Small fix to wiki:
 - CZATERIA_DEBUG=1 ./ui/ui &> ~/czateria_debug.txt
+ CZATERIA_DEBUG=1 ./ui/ui &> ~/czateria_debug.txt 2>&1

**Comment by xavery** [comment]
Pretty sure you meant `> ~/czateria_debug.txt 2>&1`, since `&>` already redirects [both stdout and stderr](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Redirecting-Standard-Output-and-Standard-Error), but it's a Bashism, so I changed that to standard POSIX syntax.

**Comment by Arek-Arek** [comment]
Hah, I assumed that ` &>` works as `& >` , you are right:) Today, I can't reproduce issue even on commit b4d96a9ff0037c58 .

**Comment by xavery** [comment]
Alright, perhaps this was a server hiccup of some kind. You know what to do in case this ever happens again. :-)

**Comment by Arek-Arek** [comment]
I just reproduced it:
```
$ CZATERIA_DEBUG=1 ui/ui 2>&1 | ts
sty 08 16:39:17 [    23.137] debug QUrl("https://czateria-api.interia.pl/scp/user/login") "nickname=redacted&roomName=Kanada&roomId=341&password=alsoredacted"
sty 08 16:39:17 [    23.430] debug {"data":{"0":"a3ff56b2eeb2baa58831e0aba238dc1d","1":"go\u015b\u0107_23827","userPerm":1,"loginDate":"08-01-2020,16:39:17","settings":{"NICK_COLOUR":"0","MAX_PRIVS":"7"}},"status":1,"code":1,"msg":"OK"}
sty 08 16:39:17 [    23.596] debug {"code":138}
sty 08 16:39:17 [    23.596] debug {"cardDate":"0","cardDescription":"","cardReasonId":0,"cardSearchAgeFrom":0,"cardSearchAgeTo":0,"cardSearchSex":"0","cardSex":"0","channelName":"Kanada","code":108,"cryptLogin":"","emotionId":0,"isHiddenMode":0,"lat":0,"localIp":"127.0.0.1","login":"redacted","lon":0,"nickColorId":0,"sessionId":"a3ff56b2eeb2baa58831e0aba238dc1d","slowLogin":false}
sty 08 16:39:17 [    23.635] debug {"subcode":1,"id":0,"isAnyRegShowAlready":false,"detailsCode":0,"type":0,"time":0,"code":150}
sty 08 16:39:17 [    23.636] info Unhandled WebSocket message :
sty 08 16:39:17  {"subcode":1,"id":0,"isAnyRegShowAlready":false,"detailsCode":0,"type":0,"time":0,"code":150}
sty 08 16:39:32 [    38.519] debug {"code":80}
```

**Comment by xavery** [comment]
This must be a server hiccup. The log clearly shows that you're sending login data for a particular nickname, but the reply from that server says that your nickname is `gość_23827`, unless that's the nickname that you were trying to use.
Hard for me to say anything else at this point. I still don't know what's the meaning of the code 150 & subcode 1 message - in any way, it seems critical, so displaying an error message asking the user to login again is the only thing that comes to mind.

**Comment by Arek-Arek** [comment]
This nickname is nick I used.

**Comment by Arek-Arek** [comment]
Hmm, I can reproduce it when nickname contains space and there is no problem when nick doesn't contain space inside. Strange.

**Comment by xavery** [comment]
Alright. It appears that the site doesn't even allow you to have spaces inside your nickname - when I try to login in with a nickname like `i like spaces`, the actual login request sent to the server is for `i_like_spaces`, so the spaces must be converted by client-side JavaScript code.
I guess the only thing to do is disallow spaces in nicknames and add an error popup if a code 150 message occurs during a chat session.

**Comment by Arek-Arek** [comment]
So... Maybe do the same, convert spaces in login to underscores like original client?

**Comment by xavery** [comment]
Yup, that's what I meant by "disallow spaces in nicknames" :)
