### ISSUE TITLE
nickname in debug log

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#42]
Hi,
... and would be nice to if you add nickname in debug log when priv message arrived or sent (code:97, subcode:1 and subcode:2), please.

**Comment by xavery** [comment]
Done in 8087b43 , but it was much easier to just include `user` if it appears. There is no filtering done according to the message's code/subcode.

**Comment by xavery** [comment]
I hope you're not trying to implement some rudimentary logging via debug messages, as they're meant for internal usage and their format might change without notice.

**Comment by Arek-Arek** [comment]
Now I see I was wrong. I tried to workarround issue #1 using something wrong tool. I expected that those information will be in json but... Debug is debug, json message should contains exactly what server send, no other things I wish to see.
Thank you, log is very usefull for me but I did mess in project.

**Comment by xavery** [comment]
No big deal. At least the logging calls look a bit better now - I managed to move most of the more repetitive code into the macros themselves.
Sorry that #1 is taking so long, but I really don't have an idea for it that I'd be totally satisfied with.

**Comment by Arek-Arek** [comment]
No need to sorry, you spend more time on tis project than I could expect.
