### ISSUE TITLE
Compilation error mainchatwindow.cpp:88:20: error: ‘class QLatin1String’ has no member named ‘arg’

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#6]
commit 549cfc48a576cf9390769730556b1c429c3bb03a introduce compilation error on my box (ubuntu 18.04).

> g++ -c -pipe -Wextra -Werror -O2 -std=c++1y -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I.. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o mainchatwindow.o mainchatwindow.cpp
mainchatwindow.cpp: In function ‘QString {anonymous}::getImageFilter()’:
mainchatwindow.cpp:88:20: error: ‘class QLatin1String’ has no member named ‘arg’
                   .arg(QString::fromUtf8(format.constData()).toLower()));

**Comment by xavery** [comment]
Thanks! I set up a simple CI workflow that runs on Ubuntu 18.04 and Windows, so you shouldn't experience issues like these in the future.

**Comment by Arek-Arek** [comment]
Thank you.
