### ISSUE TITLE
Messages sent after invitation is closed aren't delivered

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#70]
Hi!
Thank you for you work, latest commits bring many changes in application behaviour. 
I see some kind of strange behaviour in notifications. One of them is like below:
user A send invitation to talk
user B do nothing (and it gets two notification, modal window and new tab)
user A close tab with chat to user B
user A, modal window disappear but still remains question in tab
user A accept invitation but all messages sent in this chat aren't delivered to user B

**Comment by xavery** [comment]
Hi Arek, thanks for still using the program despite me not addressing much more important issues that still linger on.
I'm kind of surprised you would expect this to work, seeing how this functionality was not even available in older versions : the receiving side's modal message box and conversation tab would be closed as a response to the sender closing its conversation tab and thus "cancelling" the invitation, so there's nothing left to accept.
You're right to notice, however, that the receiving side receives the actual messages anyway, so they can just as well be displayed (or is that the default behaviour of the website? I haven't used it in a long while). The fact that the "question in tab" thing remains in the window is most definitely a bug on my side, as that should disappear when a notification is acted upon and is there only to let the user accept/reject an invitation if a native notification was not clicked before disappearing.
Please try out 93238c5c5ef0e0291dcf334351e10e7cf31b298d and see if that's what you'd like.

**Comment by Arek-Arek** [comment]
> Hi Arek, thanks for still using the program despite me not addressing much more important issues that still linger on.
There isn't any application without bug. Your app is usable and I use it.

I can't reproduce bug with undelivered messages, great:). There are still some glitches with notification, modal window and conversation tab but this is less important than initial issue.

> the receiving side's modal message box and conversation tab would be closed as a response to the sender closing its conversation tab and thus "cancelling" the invitation, so there's nothing left to accept.

This is how web client works. It makes flood of spam a little less annoying however I think that it's better to leave "conversation tab" till manual close. I often run "czateria" in background, doing something else away from desktop. When I come to desktop  after some minutes I can see that real person wrote to me and I can respond to unpatience person.

**Comment by xavery** [comment]
Thanks for reporting back, closing in this case - please feel free to report separate issues for the remaining bugs.
