### ISSUE TITLE
Number of unreaded tabs isn't recalculated after closing tab

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#75]
On title bar is displayed number of tabs with unreaded messages. If I read message and close tab with chat it is ok. If I close tab without reading message number of unreaded tabs on title bar remains the same.

**Comment by xavery** [comment]
Thanks.

**Comment by Arek-Arek** [comment]
Now work as I expect, thanks!

**Comment by Arek-Arek** [comment]
Hi,
after some time of using I can see on some windows "[1]" in title bar. Not on all, but on some of them, even when there is no chat with users inside the window.
