### ISSUE TITLE
Undesired notification about user logged out

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#78]
Hi!
Sometimes I see something like below:
- user start chat with me
- I reject chat
- after some time user logged out from czateria
- I get new tab with chat with the user, I can see what those user wrote and message that he/she logged out

It looks czateria still track users event even when chat is rejected.

**Comment by xavery** [comment]
Should be fine now. Coincidentally, this was a consequence of message caching introduced in order to fix #70.

**Comment by Arek-Arek** [comment]
It's better but I'd like to ask you to do small change.
Now when user disconnect from chat also is closing tab with chat. It's ok if I reject talk earlier but it's not good if I talk with somebody, user disconnects (e.g. due to connectivity problems) and then tab with chat is closing.

**Comment by xavery** [comment]
Alright, I reproduced it with Ubuntu 18.04 and its default Qt 5.9 (that you use, if I remember correctly), looks like it's Qt-related. Will open a separate issue soon.
