### ISSUE TITLE
Private conversation tab is sometimes closed when another party disconnects

### ISSUE THREAD

**Issue by xavery** [xavery/czateria#81]
Unfortunately there's no clear reproduction path here, and what's worse it doesn't seem like there's an obvious-ish code path that would cause closing the tab altogether when the conversation partner disconnects.
Perhaps this is related to the Qt version, since the only time I could reproduce it is under Ubuntu 18.04 with the default Qt 5.9 by doing the following :

- Open a private conversation.
- Write something to the other side and close the conversation window. Keep the other side's tab still open.
- Write something again.
- Disconnect.
- The other side's tab is closed.

**Comment by Arek-Arek** [comment]
There is another case with closing tab. This not happened every time, I don't know what makes difference. When other person closes chat with me then my tab also is closing. On some cases I got message "user closed conversation...". I'll try to find something in debug log,

**Comment by Arek-Arek** [comment]
It looks that after such case, tab of my chat is closed, when other person write something to me I don't receive it, no new tab appears, no question if I want to accept new talk.

**Comment by xavery** [comment]
Okay, I was lucky enough to finally capture a debug log while this happened.
```
[   135.701] chatsession.cpp:207 Czateria::ChatSession::~ChatSession [gość_54639973|Szkocja] > {"code":80}
[   135.716] chatsession.cpp:287 Czateria::ChatSession::onTextMessageReceived [gość_88568074|Szkocja] [user: gość_54639973] < {"subcode":15,"user":"gość_54639973","type":0,"imgWidth":0,"imgHeight":0,"msg":"","msgColorId":0,"msgIsBold":false,"msgIsItalic":false,"msgIsUnderline":false,"msgFontTypeId":0,"msgStyleId":0,"nickColorId":0,"code":97}
[   135.872] chatsession.cpp:287 Czateria::ChatSession::onTextMessageReceived [gość_88568074|Szkocja] < {"login":"gość_54639973","code":130}
[   135.872] chatsession.cpp:231 Czateria::ChatSession::rejectPrivateConversation [gość_88568074|Szkocja] [user: gość_54639973] > {"code":97,"subcode":13,"user":"gość_54639973"}
[   135.872] chatsession.cpp:287 Czateria::ChatSession::onTextMessageReceived [gość_88568074|Szkocja] [user: gość_88568074] < {"user":"gość_88568074","hasPrivs":0,"code":137}
[   135.887] chatsession.cpp:287 Czateria::ChatSession::onTextMessageReceived [gość_88568074|Szkocja] [user: gość_54639973] < {"subcode":15,"user":"gość_54639973","type":0,"imgWidth":0,"imgHeight":0,"msg":"","msgColorId":0,"msgIsBold":false,"msgIsItalic":false,"msgIsUnderline":false,"msgFontTypeId":0,"msgStyleId":0,"nickColorId":0,"code":97}
```
Everything's here and everything's fine, except the `rejectPrivateConversation` call that seems to appear out of thin air. The only place where this function is called altogether with closing the tab is `MainChatWindow::onPrivateConvNotificationRejected`, but it is - unsurprisingly - called when a notification is rejected, which is clearly not the case here, since the notification does not even appear.

I really have no idea what's happening here. Maybe I'll get to the bottom of this someday.

**Comment by xavery** [comment]
Okay, I pushed ... something. Let me know if stuff is any better.

**Comment by Arek-Arek** [comment]
Hi!
Thank you for fix!
I think there can be one more improvement:
- user A starts priv chat
- user B doesn't take any action, window with question "accept/reject?" is displayed
- user A disconnects - now this action creates new tab with message sent by user A.  

Probably this message can be discarded.

**Comment by xavery** [comment]
I introduced that as an option - look for a new check box in the main window's "Options" menu. I'm going to close this for now, feel free to report any problems as new issues.
